---

- name: User Management
  hosts: all
  user: root
  gather_facts: yes
  become: yes
  vars:
  
    user_management:
      - name: rajasoun
        comment: Raja - Dev Box
        shell: /bin/zsh
        expires: 1640991600
        groups:
          - sudo
          - docker
        ssh_keys:
          - 'ssh-rsa _REPLACE_PUBLIC_KEY_'